### ISSUE TITLE
WithTheme doesn't seem to change the theme

### ISSUE THREAD

**Issue by dfalgout** [charmbracelet/huh#100]
First, thank you all for the incredible hard work and nice design of the charm.sh suite. I'm hella diggin' it!

When I attempt to change the theme of a huh Form with .WithTheme() the form style is unchanged from the default theme.
Not only colors not changing, but also any block formatting, etc.

```
err = huh.NewMultiSelect[*App]().
  Options(options...).
  Title("Select Apps to stop").
  Value(&selectedApps).
  WithTheme(CustomTheme()).
  Run()
```
In the example screenshot below, I am also printing out the theme items and see changes in _those_ elements, but no change in the actual form theme.
<img width="819" alt="Screenshot 2024-01-14 at 11 08 27 PM" src="https://github.com/charmbracelet/huh/assets/5727132/5dc97ac7-aa68-4070-851d-33bc6399ca10">

**Comment by testinfected** [comment]
@dfalgout I had the same issue and workaround was to define the form myself, set form theme then add the widget to the form

**Comment by meowgorithm** [comment]
Off the cuff, I'd guess that this is only happening on one-off elements, i.e.

```go
huh.NewMultiSelect().
    WithTheme(customTheme()).
    Run()
```

Whereas the following works in my testing:

```go
huh.NewForm().
    WithTheme(customTheme()).
    Run()
```

**Comment by caarlos0** [comment]
my guess its a similar problem to #97

**Comment by jolheiser** [comment]
This is indeed semi-specific to using fields directly, but it's only because they use the global `Run` internally, which is the source of the issue.

In order from call site:
https://github.com/charmbracelet/huh/blob/355812cbc0888590f85b7df35efebb48ddd9fe68/field_multiselect.go#L425
https://github.com/charmbracelet/huh/blob/9cd22a8ef511b9531a89c76c43ea09b3a8245a28/run.go#L6
https://github.com/charmbracelet/huh/blob/9cd22a8ef511b9531a89c76c43ea09b3a8245a28/form.go#L84
https://github.com/charmbracelet/huh/blob/9cd22a8ef511b9531a89c76c43ea09b3a8245a28/form.go#L225-L227
https://github.com/charmbracelet/huh/blob/9cd22a8ef511b9531a89c76c43ea09b3a8245a28/group.go#L95-L97

**Comment by maaslalani** [comment]
I believe this issue should be solved if we simply check if the theme or keymap is already set on the field before overriding it. This will make things work individually and allow changing themes / keymaps for individual fields as part of a larger form as well.

**Comment by maaslalani** [comment]
This should be fixed by #123, let us know if this works for you!

If it doesn't please feel free to re-open this issue or create a new one!

**Comment by mrkwtz** [comment]
Can confirm with 0.30.0 it's still an issue, please re-open.

**Comment by maaslalani** [comment]
Apologies! Thanks for letting us know, re-opened the issue for now.

**Comment by maaslalani** [comment]
Okay after a bunch of testing I believe I have solved it correctly this time, please do try it out and let me know if everything works correctly.

* https://github.com/charmbracelet/huh/pull/219
